version: '3'
services:
  website-php-fpm:
    image: php:7.2-fpm-dev
    volumes:
      - ../website:/var/www/html
      - ../website/docker/restream-website-php-fpm/log:/var/log
    depends_on:
      - "website-db"
  website-nginx:
    image: nginx:1
    ports:
      - "4000:80"
    volumes:
      - ../website/docker/restream-website-nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ../website/public:/usr/share/nginx/html
      - ../website/docker/restream-website-nginx/log:/var/log/nginx
    depends_on:
      - "website-php-fpm"
  website-db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=q7z7xebM93clwzkqlaVT
    ports:
      - "4001:3306"
    volumes:
      - ../website/docker/restream-website-db/data:/var/lib/mysql
      - ../website/docker/restream-website-db/log:/var/log/mysql

