version: '3'
services:
  website-php-fpm:
    build: ./docker/php-fpm/
    volumes:
      - ./:/var/www/html
      - ./docker/php-fpm/log:/var/log
    depends_on:
      - "website-db"
  website-nginx:
    image: nginx:1
    ports:
      - "4000:80"
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/usr/share/nginx/html
      - ./docker/nginx/log:/var/log/nginx
    depends_on:
      - "website-php-fpm"
  website-db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=q7z7xebM93clwzkqlaVT
      - MYSQL_DATABASE=restream-landing
    ports:
      - "4001:3306"
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/log:/var/log/mysql